name: simhand
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - backcall=0.2.0
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.2.2
  - cryptography=41.0.3
  - cudatoolkit=11.3.1
  - debugpy=1.6.7
  - entrypoints=0.4
  - executing=2.1.0
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.12.0
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.15
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.2.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.21
  - pygments=2.18.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.8.18
  - python_abi=3.8
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.7.1
  - urllib3=1.26.16
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - cachetools==5.3.2
      - comet-ml==3.2.6
      - configobj==5.0.8
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.0.3
      - decorator==4.4.2
      - dulwich==0.21.7
      - easydict==1.10
      - einops==0.7.0
      - everett==3.3.0
      - fire==0.5.0
      - fonttools==4.43.1
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - future==0.18.3
      - google-auth==2.26.1
      - google-auth-oauthlib==1.0.0
      - grpcio==1.60.0
      - imageio==2.31.6
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - kornia==0.4.1
      - lazy-loader==0.4
      - lightning-lite==1.8.0
      - lightning-utilities==0.3.0
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.7.3
      - moviepy==1.0.3
      - msgpack==1.0.7
      - multidict==6.0.4
      - netifaces==0.11.0
      - networkx==3.1
      - nvidia-ml-py3==7.352.0
      - oauthlib==3.2.2
      - opencv-python==4.8.1.78
      - packaging==23.2
      - pandas==2.0.3
      - pascal-voc-writer==0.1.4
      - pkgutil-resolve-name==1.3.10
      - proglog==0.1.10
      - progress==1.6
      - protobuf==4.24.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.7
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytorch-lightning==1.8.0
      - pytorch-lightning-bolts==0.2.2
      - pytz==2023.3.post1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - referencing==0.32.0
      - requests-oauthlib==1.3.1
      - rpds-py==0.16.2
      - rsa==4.9
      - scikit-image==0.21.0
      - scikit-learn==0.23.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - torchmetrics==0.11.4
      - tqdm==4.66.1
      - tzdata==2024.2
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - wurlitzer==3.0.3
      - yacs==0.1.8
      - yarl==1.9.4
      - zipp==3.17.0